import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Navbar from './components/Navbar';
import { AuthProvider } from './components/AuthContext';
import Head from 'next/head';
import Footer from './components/Footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Log, Lap, and Over' as const,
  description: 'Generated by create next app' as const,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <Head>
          <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
          <title>
            {typeof metadata.title === 'string'
              ? metadata.title
              : 'Default Title'}
          </title>
          <meta
            name="description"
            content={
              typeof metadata.description === 'string'
                ? metadata.description
                : 'Default description'
            }
          />
        </Head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen `}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
